package com.ideo.poc.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-22T16:15:02.381+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "OperationWS", 
                  wsdlLocation = "file:/C:/labs/workspace/CXF-POC-WSDL/src/main/resources/operation.wsdl",
                  targetNamespace = "http://cxf.poc.ideo.com/") 
public class OperationWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.poc.ideo.com/", "OperationWS");
    public final static QName OperationServiceImplPort = new QName("http://cxf.poc.ideo.com/", "OperationServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/labs/workspace/CXF-POC-WSDL/src/main/resources/operation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperationWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/labs/workspace/CXF-POC-WSDL/src/main/resources/operation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperationWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperationWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperationWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OperationService
     */
    @WebEndpoint(name = "OperationServiceImplPort")
    public OperationService getOperationServiceImplPort() {
        return super.getPort(OperationServiceImplPort, OperationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperationService
     */
    @WebEndpoint(name = "OperationServiceImplPort")
    public OperationService getOperationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OperationServiceImplPort, OperationService.class, features);
    }

}
